"""Crear tabla ingresos

Revision ID: 24a7e85565e0
Revises: 323e6aa6a423
Create Date: 2026-04-18 18:00:58.030151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a7e85565e0'
down_revision: Union[str, Sequence[str], None] = '323e6aa6a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresos_id'), table_name='ingresos')
    op.drop_table('ingresos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('ingresos_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingresos_pkey'))
    )
    op.create_index(op.f('ix_ingresos_id'), 'ingresos', ['id'], unique=False)
    # ### end Alembic commands ###
