"""Crear tabla tareas

Revision ID: 8bde82379469
Revises: 24a7e85565e0
Create Date: 2026-04-18 18:33:00.398848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bde82379469'
down_revision: Union[str, Sequence[str], None] = '24a7e85565e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_ingresos_id'), table_name='ingresos')
    op.drop_table('ingresos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('ingresos_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingresos_pkey'))
    )
    op.create_index(op.f('ix_ingresos_id'), 'ingresos', ['id'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('pendiente', 'progreso', 'completado', name='estadotarea'), autoincrement=False, nullable=True),
    sa.Column('prioridad', postgresql.ENUM('baja', 'media', 'alta', name='prioridadtarea'), autoincrement=False, nullable=True),
    sa.Column('fecha_limite', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('tareas_cliente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tareas_pkey'))
    )
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    # ### end Alembic commands ###
